imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app_name: Neoproveedores
    locale: es
    contact_email: info@neoproveedores.com
    mailer:
        sender: %contact_email%

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        app_name: %app_name%
        contact_email: %contact_email%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:
        type: file
        path: %kernel.root_dir%/spool

# DoctrineMongoDBBundle Configuration
doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_server%"
    default_database: "%mongodb_database%"
    document_managers:
        default:
            mappings:
                Persistence:
                    type: annotation
                    dir: %kernel.root_dir%/../src/Persistence/Model
                    prefix: Persistence\Model

# StofDoctrineExtensionBundle Configuration
stof_doctrine_extensions:
    mongodb:
        default:
            timestampable: true

# FOSUserBundle Configuration
fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: Persistence\Model\User
    registration:
        form:
            type: app_user_registration
